# Generated by Django 4.1.1 on 2022-11-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('phoneNumber', models.CharField(max_length=200, null=True)),
                ('gen', models.CharField(max_length=200, null=True)),
                ('adrs', models.CharField(max_length=200, null=True)),
                ('District', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
